Artist implementation and ObjectCollection usage
FUMR/tidal-async pull request #46
Opened 2020-09-09 03:18 UTC by JuniorJPDJ

also other minor fixes

2020-09-09 20:34 UTC, wvffle requested changes

2020-09-09 20:34 UTC, wvffle commented on tidal_async/utils.py
> +    """Generates full title from track/album version and artist list"""
The docstring is missing a parameter in the definition
Parameter types are not required but the parameters themselves are

2020-09-09 20:34 UTC, wvffle commented on tidal_async/utils.py
>          # add featuring artists if not already
make it a `# NOTE:`
When I read it, first what came into my mind is that it's a todo

2020-09-09 20:34 UTC, wvffle commented on tidal_async/utils.py
> +    if len(artists) > 1:
Can't we just do that? It would be more readable.
```py
if len(artists) == 0:
  return # ...

if "(feat." not in title:
  # ...

return # ...
```

2020-09-09 20:34 UTC, wvffle commented on tidal_async/api.py
>  import json
I'd consider splitting api into multiple files

2020-09-09 20:34 UTC, wvffle commented on tidal_async/utils.py
> +def gen_title(track, artists=()):
It's dedicated to a track, so `gen_track_title` is better name. Albums do have titles too...

2020-09-09 20:40 UTC, JuniorJPDJ commented on tidal_async/utils.py
>          # add featuring artists if not already
I didn't even change it..

2020-09-09 20:41 UTC, JuniorJPDJ commented on tidal_async/utils.py
> +    if len(artists) > 1:
It could be even
```python
if not artists:
  ...
else:
  ...
```

2020-09-09 20:43 UTC, JuniorJPDJ commented on tidal_async/utils.py
> +def gen_title(track, artists=()):
It's not dedicated to track.
https://github.com/FUMR/tidal-async/blob/b7aead9f1a3d68850a16982f5048cb43544996a9/tidal_async/api.py#L197

2020-09-09 20:45 UTC, JuniorJPDJ commented on tidal_async/utils.py
> +    """Generates full title from track/album version and artist list"""
Really?
I'd like not to write obvious things...
It'll just add non-necessary lines and make code harder to read.

2020-09-09 20:52 UTC, wvffle commented on tidal_async/utils.py
> +def gen_title(track, artists=()):
ok

2020-09-09 20:53 UTC, wvffle commented on tidal_async/utils.py
> +def gen_title(track, artists=()):
then the parameter should be renamed

2020-09-09 20:53 UTC, wvffle commented on tidal_async/utils.py
> +    if len(artists) > 1:
there's no else required tbh

2020-09-10 15:11 UTC, JuniorJPDJ commented on tidal_async/utils.py
> +def gen_title(track, artists=()):
god, yes, wtf have i done xDD

2020-09-10 15:59 UTC, JuniorJPDJ commented on tidal_async/api.py
>  import json
I'd not
It's probably all of api.
If we will implement things which could be separated I could think about it.
What would you like to see? Every class in separate file? cmon

2020-09-11 22:22 UTC, wvffle requested changes

2020-09-11 22:22 UTC, wvffle commented on tidal_async/utils.py
> +    title = obj.title.strip()  # just in case
What is the point of this strip? It only fires when there are more than one artist. I can understand that it's to prevent double space in case of `TITLE  (feat. ...)` but L71 will return the same thing (`TITLE  (VERSION)`). This should be above L70 and `title` should be used in L71 instead of `obj.title`

2020-09-12 01:20 UTC, wvffle approved these changes

2020-09-12 01:23 UTC, wvffle commented
Can you also add `ignore=DAR101` to `/.darglint` and at least add a return description to the failing docstring?

2020-09-12 11:47 UTC, JuniorJPDJ commented
After a while of thinking: I think we could really create this docstrings as you stated, but not in this pull ;x

2020-09-12 11:48 UTC, merged