Search implementation
FUMR/tidal-async pull request #74
Opened 2021-05-20 01:48 UTC by JuniorJPDJ

I need some feedback guys ;)

ATM It depends on commit from draft PR, will be changed later.

depends on FUMR/music-service-async-interface#31
resolves #30

2021-05-23 01:54 UTC, divadsn approved these changes
The search implementation itself is very identical to the 0.7.x version of https://github.com/tamland/python-tidal, LGTM.

2021-05-23 03:29 UTC, wvffle requested changes

2021-05-23 03:29 UTC, wvffle commented on tidal_async/api.py
> +        """Generates :class:`list` of :class:`Artist`s of the :class:`Track` with their corresponding role
Compared to L262, you have to decide whether you use `list` or `:class:`list``

2021-05-23 03:29 UTC, wvffle commented on tidal_async/api.py
> +        """Generates :class:`list` of :class:`Artist`s of the :class:`Album` with their corresponding role
Same here

2021-05-23 03:29 UTC, wvffle commented on tidal_async/session.py
> +        :param types: :class:`Searchable` types or list of types, filters search results to this type,
One can `filter things out` and `restrict things to`

2021-05-23 03:29 UTC, wvffle commented on tidal_async/session.py
> +        Also allows to search for all possible objects, then this parameter is left unset or set to None/empty list.
s#is left unset or set to None/empty list.#is unset, set to None or an empty list.#

2021-05-23 03:29 UTC, wvffle commented on tidal_async/session.py
> +        (not subclass of :class:`Searchable` or :class:`TidalObject`)
s/not/not a/

2021-05-23 03:29 UTC, wvffle commented on tidal_async/session.py
> +        Maximum amount of results will be `len(types) * limit`.
is it how the Tidal API works?

2021-05-23 12:23 UTC, JuniorJPDJ commented on tidal_async/session.py
> +        Maximum amount of results will be `len(types) * limit`.
yop

2021-05-23 12:25 UTC, wvffle commented on tidal_async/session.py
> +        Maximum amount of results will be `len(types) * limit`.
hmm, kind of weird

2021-05-23 12:58 UTC, JuniorJPDJ commented on tidal_async/api.py
> +        """Generates :class:`list` of :class:`Artist`s of the :class:`Track` with their corresponding role
Well. No.

After I introduce type here, I don't use type spec in `:return:` as it's not needed.
I'll change it if you are complaining tho xD

2021-05-23 12:59 UTC, JuniorJPDJ commented on tidal_async/session.py
> +        :param types: :class:`Searchable` types or list of types, filters search results to this type,
It's not the same but your version is fitting better.

2021-05-23 13:00 UTC, JuniorJPDJ commented on tidal_async/session.py
> +        Also allows to search for all possible objects, then this parameter is left unset or set to None/empty list.
I don't like your version.
What do you think about:
then this parameter is left unset, set to None or empty list.

2021-05-23 13:02 UTC, wvffle commented on tidal_async/session.py
> +        Also allows to search for all possible objects, then this parameter is left unset or set to None/empty list.
or an

2021-05-23 13:24 UTC, JuniorJPDJ commented on tidal_async/session.py
> +        Maximum amount of results will be `len(types) * limit`.
true, but well.. I can do nothing about it as I'd like not to divide offset

2021-05-23 17:48 UTC, JuniorJPDJ commented
> The search implementation itself is very identical to the 0.7.x version of [tamland/python-tidal](https://github.com/tamland/python-tidal), LGTM.

It's totally other than python-tidal, which is closer to how API itself works.
I wanted to do this in generic way so we can use search in similar ways for every other service.
The difference is in a way it returns values.

Anyway - thanks for positive feedback @divadsn :D

2021-05-23 22:10 UTC, wvffle approved these changes

2021-05-24 00:32 UTC, JuniorJPDJ commented
I just changed dep commit to point on merged FUMR/music-service-async-interface#31.
I think it's ready to go.
I'm now playing with tests and CI on #76 so I'll fix that caching bug there - tests will not pass on this PR.

2021-05-24 00:32 UTC, merged